### ISSUE TITLE
NVIDIA MiniGo CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by alawami** [mlcommons/training_results_v0.7#5]
Running nVidia's MiniGo benchmark using run_with_docker.sh produces the following error:

Traceback (most recent call last):
  File "./ml_perf/train_loop.py", line 989, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./ml_perf/train_loop.py", line 898, in main
    tstate = minigo_train.init_train(rank, tcomm, FLAGS.model_dir)
  File "./train.py", line 247, in init_train
    sess = dual_net._get_session()
  File "./dual_net.py", line 647, in _get_session
    return tf.Session(config=session_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

**Comment by alawami** [comment]
I did not have the latest driver.

**Comment by lucasliunju** [comment]
Hi I 'm trying to run the code and I find that train_loop.py use the package "minigo_python". I cannot find this package in the source and I want to ask whether you can run the code. Thank you.
